projects:
  expoamplifystarter:
    schemaPath: src/graphql/schema.json
    includes:
      - src/api/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/amplify.ts
        docsFilePath: src/api
extensions:
  amplify:
    version: 3
