import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-controls/register';
import '@storybook/addon-a11y/register';
import '@storybook/addon-storysource/register';
import 'storybook-addon-designs/register';
import 'storybook-dark-mode/register';
import '@storybook/addon-console';
import 'storybook-addon-jsx/register';
